CLEANING DIRTY CAFE DATA

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df =pd.read_csv('dirty_cafe_sales.csv')

In [ ]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15

In [ ]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
df.nunique()

Transaction ID      10000
Item                   10
Quantity                7
Price Per Unit          8
Total Spent            19
Payment Method          5
Location                4
Transaction Date      367
dtype: int64

In [ ]:
df['Location']= df['Location'].astype(str).str.lower().str.strip()
df['Location']=df['Location'].replace(['unknown', 'error', 'nan', 'n/a', 'none'], np.nan)
df['Location'].isna().sum()
df['Location'] = df['Location'].fillna('Not Recorded')

In [ ]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,in-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,in-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,Not Recorded,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,in-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,Not Recorded,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,Not Recorded,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,in-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,in-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,in-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,in-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,Not Recorded,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,in-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,Not Recorded,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,takeaway,2023-01-15

In [ ]:
df['Total Spent']= df['Total Spent'].astype(str).str.lower().str.strip()
df['Total Spent']=df['Total Spent'].replace(['unknown', 'error', 'nan', 'n/a', 'none'], np.nan)
df['Total Spent'].isna().sum()

np.int64(502)

In [ ]:
!git config user.email

k230588@nu.edu.pk

In [ ]:
!git config --global user.email "xain.saqib@gmail.com"
!git config --global user.name "Zain Saqib"